<?php
/**
 * @file
 * tempdirectory.field_base.inc
 */


function _tempdirectory_installed_fields() {
  $field_bases = array();

  // Exported field_base: 'field_asu_directory_local_group'
  $field_bases['field_asu_directory_local_group'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_asu_directory_local_group',
    'foreign keys' => array(
      'format' => array(
        'columns' => array(
          'format' => 'format',
        ),
        'table' => 'filter_format',
      ),
    ),
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'text',
  );

  return $field_bases;
}
