<?php
/**
 * @file
 */

/**
 * Implements hook_install().
 */
function asu_clas_research_areas_install() {
  module_load_include('inc', 'asu_clas_research_areas', 'includes/actions');

  _asu_clas_research_areas_create_taxonomy();
  _asu_clas_research_areas_create_taxonomy_fields();
  _asu_clas_research_areas_add_taxonomy_terms();
  _asu_clas_research_areas_panelizer_setup();
}

/**
 * Implements hook_disable().
 */
function asu_clas_research_areas_disable() {
  return TRUE;
}

/**
 * Implements hook_uninstall().
 */
function asu_clas_research_areas_uninstall() {
  $vocab = taxonomy_vocabulary_machine_name_load('research_area');

  taxonomy_vocabulary_delete($vocab->vid);

  field_delete_field('field_research_area_image');
}
