<?php
/**
 * @file
 */

/**
 * Implements hook_install().
 */
function asu_clas_shesc_centers_install() {
  module_load_include('inc', 'asu_clas_shesc_centers', 'includes/install');
  module_load_include('inc', 'asu_clas_shesc_centers', 'includes/content');

  _asu_clas_shesc_centers_create_content_type();
  _asu_clas_shesc_centers_set_pathauto_node_pattern();
  _asu_clas_shesc_centers_create_placeholder_nodes();
  _asu_clas_shesc_centers_create_menu();
  _asu_clas_shesc_centers_upload_hero_image();
  _asu_clas_shesc_centers_create_fieldable_panels_panes();
  _asu_clas_shesc_centers_panelizer_setup();
}

/**
 * Implements hook_enable().
 */
function _asu_clas_shesc_centers_enable() {
  return TRUE;
}

/**
 * Implements hook_disable().
 */
function asu_clas_shesc_centers_disable() {
  return TRUE;
}

/**
 * Implements hook_uninstall().
 */
function asu_clas_shesc_centers_uninstall() {
  module_load_include('inc', 'asu_clas_shesc_centers', 'includes/uninstall');

  _asu_clas_shesc_centers_delete_menu();
}
