<?php
/**
 * @file
 */

/**
 * Implements hook_preprocess_html().
 */
function asu_clas_shesc_research_topics_preprocess_html(&$variables) {
  drupal_add_css(drupal_get_path('module', 'asu_clas_shesc_research_topics') . '/css/asu-clas-shesc-research-topics.css', array('group' => CSS_THEME, 'weight' => '99'));
}

/**
 * Implements hook_views_api().
 */
function asu_clas_shesc_research_topics_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'asu_clas_shesc_research_topics'),
    'template path' => drupal_get_path('module', 'asu_clas_shesc_research_topics') . '/templates',
  );
}

/**
 * Implements hook_ctools_plugin_api().
 */
function asu_clas_shesc_research_topics_ctools_plugin_api($module, $api) {
  if ($module == 'panelizer' && $api == 'panelizer') {
    return array('version' => 1);
  }
}

/**
 * Include Views exports.
 */
function asu_clas_shesc_research_topics_views_default_views() {
  $files = file_scan_directory(drupal_get_path('module', 'asu_clas_shesc_research_topics') . '/views', '/.*\.inc$/');

  foreach ($files as $filepath => $file) {
    require $filepath;

    if (isset($view)) {
      $views[$view->name] = $view;
    }
  }

  return $views;
}
