<?php
/**
 * @file
 * Code for the CLAS Paragraphs Full Image BG feature.
 */

include_once 'clas_paragraphs_full_image_bg.features.inc';


/**
 * Implements hook_theme().
 */
function clas_paragraphs_full_image_bg_theme() {
  return array(
    'paragraphs_item__clas_full_bg_image_co' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-full-bg-image-co',
      'path' => drupal_get_path('module', 'clas_paragraphs_full_image_bg') . '/theme',
    ),                                    
  );
}
