<?php
/**
 * @file
 */

/**
 * Implements hook_install().
 */
function asu_clas_shesc_study_abroad_install() {
  module_load_include('inc', 'asu_clas_shesc_study_abroad', 'includes/install');

  _asu_clas_shesc_study_abroad_panelizer_setup();
  _asu_clas_shesc_study_abroad_set_pathauto_node_pattern();
}

/**
 * Implements hook_enable().
 */
function asu_clas_shesc_study_abroad_enable() {
  return TRUE;
}

/**
 * Implements hook_disable().
 */
function asu_clas_shesc_study_abroad_disable() {
  return TRUE;
}

/**
 * Implements hook_uninstall().
 */
function asu_clas_shesc_study_abroad_uninstall() {
  return TRUE;
}
