<?php
/**
 * @file
 */

/**
 * Implements hook_preprocess_html().
 */
function asu_clas_shesc_tb_megamenu_preprocess_html(&$variables) {
  drupal_add_css(drupal_get_path('module', 'asu_clas_shesc_tb_megamenu') . '/css/asu-clas-shesc-tb-megamenu.css', array('group' => CSS_THEME, 'weight' => '99'));

  drupal_add_js(drupal_get_path('module', 'asu_clas_shesc_tb_megamenu') . '/js/asu-clas-shesc-tb-megamenu.js', array('type' => 'file', 'weight' => '99'));
}

/**
 * Implements hook_theme_registry_alter().
 *
 * Adds a preprocess function to `tb_megamenu_nav` to allow for CSS classes to be added to TB Mega Menu navigation.
 */
function asu_clas_shesc_tb_megamenu_theme_registry_alter(&$theme_registry) {
  $theme_registry['tb_megamenu']['preprocess functions'][] = 'template_preprocess_asu_clas_shesc_tb_megamenu_add_css_classes';
  $theme_registry['tb_megamenu_nav']['preprocess functions'][] = 'template_preprocess_asu_clas_shesc_tb_megamenu_add_css_classes';
}

/**
 * Implements template_preprocess_hook().
 *
 * Adds a CSS class to TB Mega Menu navigation HTML elements for styling purposes.
 */
function template_preprocess_asu_clas_shesc_tb_megamenu_add_css_classes(&$variables, $hook) {
  $system_menus = array(
    'devel',
    'main-menu',
    'management',
    'menu-mega-footer-menu',
    'navigation',
    'user-menu',
  );

  if (in_array($variables['menu_name'], $system_menus)) {
    return;
  }

  if ($variables['theme_hook_original'] == 'tb_megamenu_nav' && $variables['level'] == 0) {
    $variables['classes_array'][] = 'tb-megamenu-asu-nav-clas';
    $variables['classes_array'][] = 'tb-megamenu-asu-nav-clas-shesc';
  } else {
    $variables['classes_array'][] = 'tb-megamenu-asu-clas';
    $variables['classes_array'][] = 'tb-megamenu-asu-clas-shesc';
  }

  return $variables;
}

/**
 * Implements hook_js_alter().
 *
 * Modifies ASU Webspark TB Mega Menu JavaScript to remove inline code.
 *
 * @see webspark_megamenu_init();
 */
function asu_clas_shesc_tb_megamenu_js_alter(&$javascript) {
  foreach ($javascript as $key => $value) {
    if (isset($value['type']) && $value['type'] == 'inline') {
      if (strpos($value['data'], 'Drupal.behaviors.webspark_megamenu') !== FALSE) {
        $javascript[$key]['data'] = NULL;

        break;
      }
    }
  }
}
