<?php


include_once 'clas_paragraphs.features.inc';

/**
 * Implements hook_theme().
 */
 
function clas_paragraphs_theme() {
  return array(
    'paragraphs_item__clas_cta_footer' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-cta-footer',
      'path' => drupal_get_path('module', 'clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_two_column_image_left' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-two-column-image-left',
      'path' => drupal_get_path('module', 'clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_two_column_image_right' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-two-column-image-right',
      'path' => drupal_get_path('module', 'clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_number_highlighter' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-number-highlighter',
      'path' => drupal_get_path('module', 'clas_paragraphs') . '/theme',
    ),            
  );
}

/**
 * Implementation of hook_entity_info_alter().
 */
function clas_paragraphs_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['clas_paragraph_pane'] = array(
    'label' => t('CLAS Paragraph Pane'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'clas_paragraphs') . '/images/icon_clas_paragraph_pane.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_pane_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/clas-paragraph-pane',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

