<?php

/**
 * @file
 * Main module file asu_clas_paragraphs.module
 */

include_once 'asu_clas_paragraphs.features.inc';

/**
 * Implementation of hook_entity_info_alter().
 */
function asu_clas_paragraphs_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['clas_paragraph_pane'] = array(
    'label' => t('CLAS Paragraph Pane'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => drupal_get_path('module', 'clas_paragraphs') . '/images/icon_clas_paragraph_pane.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_pane_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/clas-paragraph-pane',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_preprocess_html().
 */
function asu_clas_paragraphs_preprocess_html(&$variables) {
  $stylesheets = array(
    '/css/clas-common.css',
    '/css/clas-cta-footer.css',
    '/css/clas-number-highlighter.css',
    '/css/clas-quotes-carousel.css',
    '/css/clas-starburst-gold-carousel.css',
    '/css/clas-starburst-gray-carousel.css',
    '/css/clas-two-column-gold-starburst-right.css',
    '/css/clas-two-column-image-left.css',
    '/css/clas-two-column-image-right.css',
    '/css/clas-two-column-photos.css',
    '/css/clas-two-column-image-right-two.css',
    '/css/clas-two-column-video-left.css',
    '/css/clas-edgy-paragraph-gold-icon.css',
    '/css/clas-edgy-paragraph-background-cover.css',
    '/css/clas-discipline-icon-grid.css',
    '/css/clas-carousel-background-cover.css',
    '/css/clas-media-object.css',
    '/css/clas-discipline-icon-grid-w-text.css',
    '/css/clas-full-background-image-callout.css',
  );

  foreach ($stylesheets as $stylesheet) {
    drupal_add_css(drupal_get_path('module', 'asu_clas_paragraphs') . $stylesheet, array('group' => CSS_THEME, 'weight' => '99'));
  }

  drupal_add_js(array('asu_clas_paragraphs' => array('basePath' => '/' . drupal_get_path('module', 'asu_clas_paragraphs'))), 'setting');
}

/**
 * Implements hook_theme().
 */
function asu_clas_paragraphs_theme() {
  return array(
    'paragraphs_item__clas_cta_footer' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-cta-footer',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_two_column_image_left' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-two-column-image-left',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_two_column_image_right' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-two-column-image-right',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_number_highlighter' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-number-highlighter',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_quotes_carousel' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-quotes-carousel',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_starburst_gray_carousel' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-starburst-gray-carousel',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_starburst_gold_carousel' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-starburst-gold-carousel',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_two_col_gold_sb_right' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-two-col-gold-sb-right',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_two_column_photos' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-two-column-photos',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_two_column_image_right_2' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-two-column-image-right-option-two',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_two_column_video_left' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-two-column-video-left',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_edgy_paragraph_gold_icon' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-edgy-paragraph-gold-icon',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_edgy_paragraph_bg_cover' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-edgy-paragraph-background-cover',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_discipline_icon_grid' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-discipline-icon-grid',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_carousel_background_cover' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-carousel-background-cover',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_media_object' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-media-object',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_discipline_icon_grid_w_text' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-discipline-icon-grid-w-text',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
    'paragraphs_item__clas_full_bg_image_co' => array(
      'render element' => 'elements',
      'template' => 'paragraphs-item--clas-full-bg-image-co',
      'path' => drupal_get_path('module', 'asu_clas_paragraphs') . '/theme',
    ),
  );
}

/**
 * Helper function for taking a group of links and separating them out with a pipe
 * @param array $items - an array of items to convert to string separated by pipes
 */
function asu_clas_paragraphs_format_with_pipes($items) {
  $items_formatted = '';
  if (!empty($items)) {
    foreach($items as $item) {
      $items_formatted .= l($item['title'], $item['url'], array('html' => TRUE, 'attributes' => array('class' => array('pipe-link')))).' | ';
    }
    $items_formatted = rtrim($items_formatted, '| ');
  }
  return $items_formatted;
}

/**
 * Helper function that returns webspark column classes based on how many columns we're needing
 * @param string $template_type - string with the template type - options : "Two Columns", "Four Columns"
 */
function asu_clas_paragraphs_format_column_classes($template_type = 'Two Columns') {
  if ($template_type == 'Four Columns') {
    $classes = 'col-xs-12 col-sm-6 col-md-3';
  }
  else {
    $classes = 'col-xs-12 col-sm-6 col-md-6';
  }
  return $classes;
}
