<?php

/**
 * Implements hook_js_alter().
 */
function asu_clas_webspark_megamenu_js_alter(&$javascript) {
	// Replace the JavaScript from Webspark Mega Menu with our own.
	$path = drupal_get_path('module', 'asu_clas_webspark_megamenu') . '/js/asu_clas_webspark_megamenu.js';

	$javascript['profiles/openasu/modules/webspark_featurescustom/webspark_megamenu/js/webspark_megamenu.js']['data'] = $path;
}
