<?php
/**
 * @file
 */

/**
 * Implements hook_preprocess_html().
 */
function asu_clas_psychology_labs_preprocess_html(&$variables) {
  drupal_add_css(drupal_get_path('module', 'asu_clas_psychology_labs') . '/css/asu-clas-psychology-labs.css', array('group' => CSS_THEME, 'weight' => '99'));
}

/**
 * Implements hook_views_api().
 */
function asu_clas_psychology_labs_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'asu_clas_psychology_labs'),
    'template path' => drupal_get_path('module', 'asu_clas_psychology_labs') . '/templates',
  );
}

/**
 * Implements hook_ctools_plugin_api().
 */
function asu_clas_psychology_labs_ctools_plugin_api($module, $api) {
  if ($module == 'panelizer' && $api == 'panelizer') {
    return array('version' => 1);
  }
}

/**
 * Include Views exports.
 */
function asu_clas_psychology_labs_views_default_views() {
  $files = file_scan_directory(drupal_get_path('module', 'asu_clas_psychology_labs') . '/views', '/.*\.inc$/');

  foreach ($files as $filepath => $file) {
    require $filepath;

    if (isset($view)) {
      $views[$view->name] = $view;
    }
  }

  return $views;
}

/**
 * Implements hook_form_alter().
 */
function asu_clas_psychology_labs_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && $form_state['view']->name == 'research_labs' && $form_state['view']->current_display == 'filter') {
    // Change value of submit button from 'Apply' to 'Filter'.
    $form['submit']['#value'] = 'Filter';
  }
}
