<?php
// Plugin definition
$plugin = array(
  'title' => t('Moscone Plus'),
  'icon' => 'mosconeplus.png',
  'category' => t('Panopoly'),
  'theme' => 'mosconeplus',
  'css' => 'mosconeplus.css',
  'regions' => array(
    'header' => t('Header'),
    'sidebar' => t('Sidebar'),
    'rowone' => t('Row One'),
    'rowtwo' => t('Row Two'),
    'rowthree' => t('Row Three'),        
    'footer' => t('Footer'),
  ),
);
