<?php
//! Drupal hook implementations.

//! Tokens:

/**
 * Implementation of hook_token_info().
 **/
function classocial_token_info() {
  $info = array();

  $info['types']['classocial'] = array(
    'name' => t('classocial tokens'),
    'description' => t("classocial tokens."),
  );

/*  $info['tokens']['classocial']['vertical'] = array(
    'name' => t("Social button bar, vertical"),
    'description' => t("Social button bar, vertical layout."),
  );*/

  $info['tokens']['classocial']['horizontal'] = array(
    'name' => t("Social button bar, horizontal"),
    'description' => t("Social button bar, horizontal layout."),
  );

  return $info;
}

/**
 * Implementation of hook_tokens().
 **/
function classocial_tokens($type, $tokens, $data = array(), $options = array()) {
  $replacements = array();

  if ($type == 'classocial') {
    $vertical = classocial_buttons('vertical');
    $horizontal = classocial_buttons('horizontal');

    // Loop through the available tokens.
    foreach ($tokens as $name => $original) {
      // Find our custom tokens by name.
      switch ($name) {
        case 'vertical':
          // Give our token its value!
          $replacements[$original] = render($vertical);
          break;

        case 'horizontal':
          // Give our token its value!
          $replacements[$original] = render($horizontal);
          break;
      }
    }
  }

  return $replacements;
}


//! Blocks:

/**
 * Implements hook_block_info().
 *
 * This hook declares which blocks are provided by the module.
 */
function classocial_block_info() {
/*  $blocks['vertical'] = array(
    'info' => t('Social buttons: vertical layout'),
    'status' => FALSE,
    'region' => 'sidebar_second',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );*/

  $blocks['horizontal'] = array(
    // info: The name of the block.
    // 'info' => t('Social buttons: horizontal layout'),
    'info' => t('CLAS Share: Social Buttons'),
    'status' => FALSE,
    'region' => 'sidebar_second',
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );

  return $blocks;
}


/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function classocial_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  $block = array();

  switch ($delta) {
    case 'vertical':
      $block['subject'] = NULL;
      $block['content'] = classocial_buttons('vertical');
      break;

    case 'horizontal':
      $block['subject'] = NULL;
      $block['content'] = classocial_buttons('horizontal');
      break;
  }

  return $block;
}


//! Module-specific code

/* The following links borrowed from https://github.com/cferdinandi/social-sharing

<a target="_blank" href="https://twitter.com/intent/tweet?text=YOUR-TITLE&url=YOUR-URL&via=TWITTER-HANDLE">Tweet</a>

<a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=YOUR-URL">Share on Facebook</a>

<a target="_blank" href="https://plus.google.com/share?url=YOUR-URL">Plus on Google+</a>

<a target="_blank" href="https://www.linkedin.com/shareArticle?mini=true&url=YOUR-URL&title=YOUR-TITLE&summary=YOUR-SUMMARY&source=YOUR-URL">Share on LinkedIn</a>

<a target="_blank" href="https://pinterest.com/pin/create/button/?url=YOUR-URL&description=YOUR-DESCRIPTION&media=YOUR-IMAGE-SRC">Pin on Pinterest</a>

<a target="_blank" href="https://vk.com/share.php?url=YOUR-URL&title=YOUR-TITLE&description=YOUR-DESCRIPTION&image=YOUR-IMAGE-SRC&noparse=true">Share on VK</a>

<a target="_blank" href="https://www.xing-share.com/app/user?op=share;sc_p=xing-share;url=YOUR-URL">Share on Xing</a>

<a target="_blank" href="http://www.tumblr.com/share/link?url=YOUR-URL&description=YOUR-DESCRIPTION">Share on Tumblr</a>

<a target="_blank" href="http://www.reddit.com/submit?url=YOUR_URL&title=YOUR_TITLE">Share on Reddit</a>

*/

/**
 * Return a render array containing markup for the social sharing buttons.
 *
 * @param $vertical
 *   Do we want the buttons side-by-side (horizontal) or under each other
 *   (vertical)?
 * @return
 *   Render array containing the social buttons.
 */
function classocial_buttons($layout = 'vertical', $msg_parts = array()) {
  global $base_url;

  $modulepath = drupal_get_path('module', 'classocial');
  $horizontal = ($layout == 'horizontal');

  $tag = $horizontal ? 'span' : 'div';
  $horizontal_class = $horizontal ? ' inline' : '';

  $current_page_full_url = $base_url . '/' . request_path();

  $msg_parts_defaults = array(
    'subject' => drupal_get_title(),
    'body' => $current_page_full_url,
    'url' => $current_page_full_url,
  );

  $msg_parts = array_merge($msg_parts_defaults, $msg_parts);

  // URL encode so the strings can be used inside URLs;
  foreach ($msg_parts as $key => $msg) {
    $msg_parts[$key] = rawurlencode($msg);
  }

  $subject = $msg_parts['subject'];
  $body    = $msg_parts['body'];
  $url     = $msg_parts['url'];

  $output = array(
    '#prefix' => '<div class="clas-social-wrapper well"><h3 class="h3-social">share: </h3><hr class="hr-social" /><ul class="social-icons icon-circle list-unstyled list-inline">',
    '#suffix' => '</ul></div>',
    '#attached' => array(
      'css' => array($modulepath . '/css/classocial.min.css'),
      'js' => array($modulepath . '/js/ics.deps.min.js'),
    ),
  );

  //$btn_classes = array('btn', 'btn-info', 'btn-xs');
  $btn_classes = array('clas-social-link');

  if ($layout == 'vertical') {
    $btn_classes[] = 'btn-block';
  }


  // mailto: link for email
  $link = "mailto:?subject=$subject&body=$body";
  $text = '<i class="fa fa-envelope fa-lg"></i>';
  $output['email'] = array(
    '#prefix' => "<li>",
    '#suffix' => "</li>",
    '#markup' => l($text, $link, array(
  	  'html' => TRUE,
  	  'attributes' => array(
    	  'class' => $btn_classes,
  	  )
	  )),
  );

  // Facebook share:
  $link = "https://www.facebook.com/sharer/sharer.php?u=$url";
  $text = '<i class="fa fa-facebook fa-lg"></i>';
  $output['facebook'] = array(
    '#prefix' => "<li>",
    '#suffix' => "</li>",
    '#markup' => l($text, $link, array(
  	  'html' => TRUE,
  	  'attributes' => array(
    	  'target' => '_blank',
    	  'class' => $btn_classes,
  	  )
	  )),
  );

  // Twitter share:
  $twitter_msg = $subject . ' -'; // Twitter adds the $url after this automatically.
  $link = "https://twitter.com/intent/tweet?text=$twitter_msg&url=$url";
  $text = '<i class="fa fa-twitter fa-lg"></i>';
  $output['twitter'] = array(
    '#prefix' => "<li>",
    '#suffix' => "</li>",
    '#markup' => l($text, $link, array(
      'html' => TRUE,
      'attributes' => array(
        'target' => '_blank',
        'class' => $btn_classes,
      )
    )),
  );

  // Google Plus share:
  $link = "https://plus.google.com/share?url=$url";
  $text = '<i class="fa fa-google-plus fa-lg"></i>';
  $output['gplus'] = array(
    '#prefix' => "<li>",
    '#suffix' => "</li>",
    '#markup' => l($text, $link, array(
  	  'html' => TRUE,
  	  'attributes' => array(
    	  'target' => '_blank',
    	  'class' => $btn_classes,
  	  )
	  )),
  );

  // LinkedIn share:
  $link = "https://www.linkedin.com/shareArticle?mini=true&url=$url";
  $text = '<i class="fa fa-linkedin fa-lg"></i>';
  $output['linkedin'] = array(
    '#prefix' => "<li>",
    '#suffix' => "</li>",
    '#markup' => l($text, $link, array(
      'html' => TRUE,
      'attributes' => array(
        'target' => '_blank',
        'class' => $btn_classes,
      )
    )),
  );

  // -- Calendar icon if asu_event type
  $our_alias = $_GET['q'];
  $our_normal_path = drupal_get_normal_path($our_alias);
  $our_normal_path_parts = explode("/",$our_normal_path);

  if (count($our_normal_path_parts)>1){

    $nid = $our_normal_path_parts[1];
    //echo $nid;
    $node = node_load($nid);
    $our_node_type = node_type_get_name($node);

    //echo $our_node_type;

    if ($our_node_type == "ASU Event"){
  		if(isset($node->field_asuevent_nid['und'][0]['value'])) {
  		  $asu_event_id = $node->field_asuevent_nid['und'][0]['value'];

  		  // Calendar Add:
  		  $link = "https://asuevents.asu.edu/calendar/ical/".$asu_event_id;
  		  $text = '<i class="fa fa-calendar fa-lg"></i>';
  		  $output['addtocalendar'] = array(
    			'#prefix' => "<li>",
    			'#suffix' => "</li>",
    			'#markup' => l($text, $link, array(
    			  'html' => TRUE,
    			  'attributes' => array(
    				      'target' => '_blank',
    				      'class' => $btn_classes,
    			  )
    			)),
		    );
		  }
      else {
  		  $link = "";
  		  $text = '';
        $eventargs = "'".$node->title."', '";
        $eventargs .= $node->body['und'][0]['value']."', '";
        $eventargs .= $node->field_asuevent_location['und'][0]['value']."', '";
        $eventargs .= $node->field_asuevent_date['und'][0]['value']."', '";
        $eventargs .= $node->field_asuevent_date['und'][0]['value2']."'";
  		  $output['addtocalendar'] = array(
    			'#prefix' => "<li><script>var socialcal = ics(); socialcal.addEvent(".$eventargs.");</script><i class='fa fa-calendar fa-lg' id='eventics' style='cursor:pointer;'></i>",
    			'#suffix' => '<script>(function ($, Drupal) {$("#eventics").click(function() {socialcal.download("Event");});})(jQuery, Drupal);</script></li>',
    			'#markup' => l($text, $link, array(
    			  'html' => TRUE,
    			  'attributes' => array(
    				      'target' => '_blank',
    				      'class' => $btn_classes,
    			  )
    			)),
		    );
      }

    };

  };
  // -- Calendar icon if asu_event type

  // Nested, so that Drupal's block system wraps the markup more as expected.
  return array(
    'classocial' => $output,
  );
}


/**
 * @file
 * Code for the ASU News and Event Type Feature feature.
 */

include_once 'classocial.features.inc';
